source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

pod 'Typhoon', '~> 3.3'
pod 'TPKeyboardAvoiding', '~> 1.2.3'
pod "AFNetworking", "~> 2.6.3"
pod 'UICKeyChainStore'
pod 'THNotesTextView', '~> 1.0.0'
pod 'ARAlertController'